### PR TITLE
fix(dropdown-menu-item): pass rel attribute from menu item to anchor tag

### LINKED ISSUE #279: DropdownMenuItem: MenuItem as link is missing rel attribute
**Expected behavior**
Adding a `rel` attribute on the `pharos-dropdown-menu-item` is passed down to the underlying `a` tag

**Actual behavior**
`rel` attribute is omitted from the anchor tag inside the `pharos-dropdown-menu-item`

**Steps to reproduce the issue**

1. Add a standard dropdown to the page
2. Add a `rel="noopener"` attribute to one of the menu items
3. Inspect the DOM and see that it's not present

**Screenshots or code**
https://codesandbox.io/s/hungry-meninsky-e3ye8?file=/src/components/HelloWorld.vue

image

**Pharos version**
11.1.0

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 96

**Additional information**
Add any additional notes or further context about the issue here.

### PR DESCRIPTION
**Pull request by satya-achanta-venkata**
**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?

**What does this change address?**

Fixes #279

**How does this change work?**
Whenever we assign `rel` attribute to DropdownMenuItem, attribute value will be passed to underlying anchor tag

### CODE REVIEW

File: packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.ts [hunk 1]
```diff
@@ -56,6 +57,13 @@ export class PharosDropdownMenuItem extends ScopedRegistryMixin(FocusMixin(Pharo
   @property({ type: String, reflect: true })
   public target: '_blank' | '_parent' | '_self' | '_top' = '_self';
 
+  /**
+   * Indicates the type of link.
```
Comment (daneah) [inline packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.ts:61]: Perhaps more accurately, quoting more or less from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel):

```suggestion
   * Indicates the relationship of the resource to the current document.
```

**Review by daneah — APPROVED** [review]

**Review by SMQuazi — APPROVED** [review]
