### PR TITLE
Tabs: move selected state management to pharos-tabs

### LINKED ISSUE #462: Tabs: Tab selection firing twice
**Expected behavior**
On tab clicked, tab selected event fires a single time

**Actual behavior**
On tab click, tab selection event fires twice. For our specific purposes, this means a duplicate log event is emitted. 

**Steps to reproduce the issue**

See output of actions on events page within Pharos
https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-tabs--events

**Screenshots or code**

https://user-images.githubusercontent.com/13315416/205705648-f405f3e2-7e95-4b16-b08c-49e298bb6a2c.mov

**Pharos version**
[v12.16.0](https://github.com/ithaka/pharos/releases/tag/%40ithaka%2Fpharos%4012.16.0)

**Your environment**

- OS: macOS, probably any
- Browser: Chrome, probably any 
- Version: 108, probably any

**Additional information**
Suspect the behavior was introduced in [v12.15.0](https://github.com/ithaka/pharos/releases/tag/%40ithaka%2Fpharos%4012.15.0)

### PR DESCRIPTION
**Pull request by chrisjbrown**
**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [x] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [x] Yes
- [ ] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**

Fixes #462

**How does this change work?**

A new attribute of pharos-tabs will manage the `selected-tab`, which refers to the index of the selected tab in the tablist.

On initial render, the `selected-tab` attribute of `pharos-tabs` will be used (which defaults to 0) to set the correct `pharos-tab` as `selected`

After updates, `selected-tab` prop on `pharos-tabs` should be used to programmatically update the selected tab. When a `pharos-tab` is clicked it dispatches an event and lets the parent manage its state. When a `pharos-tab` is clicked and it is already `selected` it does not dispatch an event to the parent.

### CODE REVIEW

File: packages/pharos/src/components/tabs/pharos-tab.ts [hunk 1]
```diff
@@ -63,7 +60,9 @@ export class PharosTab extends PharosElement {
   }
 
   private _handleClick(): void {
-    this._triggerSelectedEvent();
+    if (!this.selected) {
+      this._triggerSelectedEvent();
+    }
```
Comment (chrisjbrown) [inline packages/pharos/src/components/tabs/pharos-tab.ts:65]: i wonder if this conditional check should be here or in the parent 🤔

Comment (michael-iden) [reply packages/pharos/src/components/tabs/pharos-tab.ts:65]: I'm good with cutting off any additional logic as soon as possible as we know its not necessary. I think we could change this to happen higher up as a patch if we notice a problem though.

**Review by michael-iden — APPROVED** [review]

File: packages/pharos/src/components/tabs/pharos-tabs.ts [hunk 2]
```diff
@@ -29,6 +31,13 @@ export class PharosTabs extends PharosElement {
   @property({ type: Boolean, reflect: true, attribute: 'panel-separator' })
   public panelSeparator = false;
 
+  /**
+   * Indicates if the tab is selected-tab.
```
Comment (daneah) [inline packages/pharos/src/components/tabs/pharos-tabs.ts:35]:
```suggestion
   * The 0-based index of the tab that is initially selected.
```

**Review by daneah — CHANGES_REQUESTED** [review]

**Review by daneah — APPROVED** [review]
