### PR TITLE
fix(select): set the selection when a value is initially passed

### LINKED ISSUE #168: Select: option should be selected if the value of select matches option value
**Expected behavior**
the value of the of the select set the selected option

**Actual behavior**
the pharos-select selected option is 1  event though the value of the select is 2

**Steps to reproduce the issue**
https://codesandbox.io/s/frosty-currying-rv34u?file=/src/components/HelloWorld.vue

**Pharos version**
9.x

**Your environment**
macOS
firefox

### PR DESCRIPTION
**Pull request by Niznikr**
**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?

**What does this change address?**
Fixes #168 

**How does this change work?**

- set the selection when a value is initially passed

**Additional context**
The `value` attribute is not a standard for native selects. [Frameworks such as React and Vue](https://reactjs.org/docs/forms.html#the-select-tag) use it to improve developer experience. Because our component has to render options instead of using a slot, `value` does not get reflected on initial render and so we have to manually set it.

### CODE REVIEW

File: packages/pharos/src/components/select/pharos-select.ts [hunk 1]
```diff
@@ -45,7 +45,11 @@ export class PharosSelect extends ObserveChildrenMixin(FormMixin(FormElement)) {
   }
 
   protected firstUpdated(): void {
-    this._setOption();
+    if (!this.value) {
+      this._setOption();
+    } else {
+      this._select.value = this.value;
+    }
```
Comment (chrisjbrown) [inline packages/pharos/src/components/select/pharos-select.ts:52]: would we want to check if `this.value` exists as a possible `option`? 
or is it kinda on the consumer at that point? 😅

Comment (Niznikr) [reply packages/pharos/src/components/select/pharos-select.ts:52]: Hmm I don't think setting `value` on the select will do anything if it doesn't exist but I can check what React does.

Comment (Niznikr) [reply packages/pharos/src/components/select/pharos-select.ts]: Added a check

**Review by daneah — APPROVED** [review]

**Review by chrisjbrown — APPROVED** [review]
