### PR TITLE
fix(input-group): shift validity icon placement

### LINKED ISSUE #204: Input Group: Validation state showing behind icon
**Expected behavior**
When leveraging an Input Group in combination with field validation, expectation is that the in-field valid/invalid indicator would show to the left of the icon button.

**Actual behavior**
When passing `validated={true}` or ` invalidated={true}` on the `PharosInputGroup` element so that the text input can be styled based on the validation state of the user's entry, the indicator is displaying behind the icon button, in this example the search icon button.

**Steps to reproduce the issue**

1. Create an  instance of a `PharosInputGroup` that contains `<PharosButton icon="search" />`
2. Set the ` invalidated` parameter on the `PharosInputGroup` to `true`
3. Observe the invalid icon is showing behind the magnifying glass icon

**Screenshots or code**
**Error**
Screen Shot 2021-08-13 at 5 19 44 PM

**Success**
Screen Shot 2021-08-13 at 5 33 43 PM

**React/Typescript Component Example**

```typescript
import { useState } from "react";
import { PharosInputGroup, PharosButton } from "@ithaka/pharos/lib/react-components";

export const checkEmailField = (emailAddress: string): boolean => {
    const regExpTester = new RegExp(
        /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    );

    return regExpTester.test(emailAddress);
};

export interface iUserEmailSearchProps {
    searchLoading: boolean;
}

export const UserEmailSearch = ({ searchLoading }: iUserEmailSearchProps): JSX.Element => {
    const [userSearch, setUserSearch] = useState<string>("");
    const [valid, setValid] = useState<boolean | null>(null);
    const clearSearch = (): void => {
        setUserSearch("");
        setValid(null);
    };
    const validateEmail = (): void => {
        if (userSearch === "") {
            setValid(null);
        } else {
            setValid(checkEmailField(userSearch));
        }
    };
    const sendSearchRequest = (): void => {
        if (userSearch.length) {
            if (!checkEmailField(userSearch)) {
                setValid(false);
            } else {
                setValid(true);
                // Make search call
            }
        }
    };

    return (
        <PharosInputGroup
            hideLabel
            placeholder="Search by email address"
            validated={valid === null ? false : valid}
            invalidated={valid === null ? false : !valid}
            message={valid !== null && !valid ? "You must enter a valid email address." : ""}
            value={userSearch}
            onBlur={() => validateEmail()}
            onInput={event => setUserSearch((event.target as HTMLInputElement).value)}
        >
            <slot slot="label">User Search</slot>
            <PharosButton 
                name="close" 
                icon="close" 
                disabled={searchLoading} 
                variant="subtle" 
                label="close" 
                onClick={() => clearSearch()} 
            />
            <PharosButton
                name="search"
                icon="search"
                disabled={searchLoading}
                variant="subtle"
                label="search"
                onClick={() => sendSearchRequest()}
            />
        </PharosInputGroup>
    );
};
```

**Pharos version**
10.6.0

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 91.0.4472.164

### PR DESCRIPTION
**Pull request by daneah**
**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?

**What does this change address?**

Fixes #204 

**How does this change work?**

* Consider the width of the appended input group content (like buttons) when determining the icon's placement and the input's padding.
* Add a story to show validity for input groups to identify regressions

**Additional context**

I replaced instances of `super['_input']` with `this._input` and made `_input` a protected instead of private member of the base class. This feels fine encapsulation-wise and makes the inheritance feel more smooth.

### CODE REVIEW

File: packages/pharos/src/components/input-group/pharos-input-group.ts [hunk 1]
```diff
@@ -44,14 +44,15 @@ export class PharosInputGroup extends PharosTextInput {
...
-      super[
-        '_input'
-      ].style.paddingLeft = `calc(${PharosSpacingThreeQuartersX} + ${this._prependGroupWidth}px)`;
+      this._input.style.paddingLeft = `calc(${PharosSpacingThreeQuartersX} + ${this._prependGroupWidth}px)`;
     }
     if (changedProperties.has('_appendGroupWidth')) {
-      super[
-        '_input'
-      ].style.paddingRight = `calc(${PharosSpacingThreeQuartersX} + ${this._appendGroupWidth}px)`;
+      if (this._inputIcon) {
```
Comment (Niznikr) [inline packages/pharos/src/components/input-group/pharos-input-group.ts:50]: Noticed the icon does not get placed correctly when `validated` and `invalidated` are added dynamically with the dev tools. We should probably react when either properties are true as well.

File: packages/pharos/src/components/input-group/pharos-input-group.ts [hunk 2]
```diff
@@ -83,17 +84,13 @@ export class PharosInputGroup extends PharosTextInput {
 
   private _adjustPadding(event: FocusEvent) {
     const amount = event.type === 'focus' ? -1 : 1;
-    super['_input'].style.paddingLeft = `${
-      parseInt(
-        window.getComputedStyle(super['_input'], null).getPropertyValue('padding-left'),
-        10
-      ) + amount
+    this._input.style.paddingLeft = `${
```
Comment (Niznikr) [inline packages/pharos/src/components/input-group/pharos-input-group.ts:87]: The invalidated input group text shifts a little on focus. Probably because it already has a 2px border without focus. Might need to adjust the logic on line 86.

**Review by Niznikr — APPROVED** [review]
