### PR TITLE
Radio, Checkbox: Fix group label

### LINKED ISSUE #651: Checkbox & radio group accName includes description/error information
**Expected behavior**
The checkbox & radio group accessible name (accName) calculation should include only the name and purpose of the grouping and any help text or error information should be conveyed via it's accessible description (accDesc) calculation. 

**Actual behavior**
The accName is calculated by concatenating both the group's name, through the `legend` element, as well as including the error information (when exposed). This creates a verbose name for the group with information that should be considered part of it's description.

**Steps to reproduce the issue**
1. Review the [Forms / Checkbox Group - Validity](https://pharos.jstor.org/storybooks/wc/?path=/story/forms-checkbox-group--validity) variant
2. Using the browsers inspect tool, observe the calculated accName of the checkbox group
3. Verify the full accName includes the error information.

**Screenshots or code**
Screenshot 2023-11-27 at 10 24 33 AM

**Pharos version**
13.2.2

**Your environment**

- OS: macOS 13.6.2
- Browser: Chrome 119, Firefox 119

**Additional information**
The error information would be better served to be programmatically associated with the group via the `aria-describedby` attribute. 

Examples referenced during testing:
- https://spectrum.adobe.com/page/checkbox-group/
- https://opensource.adobe.com/spectrum-web-components/components/field-group/

### PR DESCRIPTION
**Pull request by sirrah-tam**
**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [ ] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**

Fixes #651 

This change ensures the associated hint text or error messages for radio & checkbox groups are calculated as the group's accessible description (accDesc) rather than as part of the accessible name (accName).

**How does this change work?**
The concatenation for the label as well as the `aria-labelledby` attribute is removed to allow the `legend` element to calculate the group's accName. Adding the `aria-describedby` attribute with its value referencing the ID `message` will ensure that any hint text or error message that is supplied gets added as the groups accDesc.

### CODE REVIEW

File: packages/pharos/src/components/checkbox-group/pharos-checkbox-group.ts [hunk 1]
```diff
@@ -81,16 +81,11 @@ export class PharosCheckboxGroup extends FormElement {
...
-    if (this.messageId) {
-      labels.push(this.messageId);
-    }
-
     return html`
       <fieldset
         class="checkbox-group checkbox-group--${this.horizontal ? 'horizontal' : 'vertical'}"
         aria-invalid="${this.invalidated}"
-        aria-labelledby="${labels.join(' ')}"
+        aria-describedby="message"
```
[the remark this answers is not in the document]
Comment (sirrah-tam) [reply packages/pharos/src/components/checkbox-group/pharos-checkbox-group.ts:88]: As far as I can tell, it looks like it does only supply a value if there is a message, so that's promising. We may need to review some additional use cases to be sure.

[the remark this answers is not in the document]
Comment (brentswisher) [reply packages/pharos/src/components/checkbox-group/pharos-checkbox-group.ts]: 🤔 [this file](https://github.com/sirrah-tam/pharos/blob/5a7e6107e5ea2e47929d1c2b5b2053ccb46864f7/packages/pharos/src/components/base/form-element.ts#L104) seems to be where the messageId is populated from. The logic here is a little convoluted and I would have to look into it a it more to be sure.

File: packages/pharos/src/components/checkbox-group/pharos-checkbox-group.ts [hunk 2]
```diff
@@ -81,16 +81,11 @@ export class PharosCheckboxGroup extends FormElement {
...
-    if (this.messageId) {
-      labels.push(this.messageId);
-    }
-
     return html`
       <fieldset
         class="checkbox-group checkbox-group--${this.horizontal ? 'horizontal' : 'vertical'}"
         aria-invalid="${this.invalidated}"
-        aria-labelledby="${labels.join(' ')}"
+        aria-describedby="${this.messageId}"
```
Comment (daneah) [inline packages/pharos/src/components/checkbox-group/pharos-checkbox-group.ts:88]: You'll need to wrap this in the `ifdefined` Lit directive, as `this.messageId` can be `undefined` and we don't want to render `aria-describedby="undefined"` literally.

**Review by daneah — APPROVED** [review]

**Review by brentswisher — CHANGES_REQUESTED** [review]
Code looks good! Could a unit test be added to verify the `aria-describedby` is added/removed as expected?

File: packages/pharos/src/components/checkbox-group/pharos-checkbox-group.test.ts [hunk 3]
```diff
@@ -135,6 +135,28 @@ describe('pharos-checkbox-group', () => {
...
+            ><span slot="label">Checkbox 2</span></test-pharos-checkbox
+          >
+        </test-pharos-checkbox-group>
+      `
+    );
+    const groupDescID = component.renderRoot
+      .querySelector('fieldset')
+      ?.getAttribute('aria-describedby');
+
+    expect(component.renderRoot.querySelector('#' + groupDescID)?.textContent)?.to.equal(text);
```
Comment (daneah) [inline packages/pharos/src/components/checkbox-group/pharos-checkbox-group.test.ts:157]:
```suggestion
    expect(component.renderRoot.querySelector(`#${groupDescID}`)?.textContent)?.to.equal(text);
```

File: packages/pharos/src/components/radio-group/pharos-radio-group.test.ts [hunk 4]
```diff
@@ -328,6 +328,28 @@ describe('pharos-radio-group', () => {
...
+            ><span slot="label">Radio 2</span></test-pharos-radio-button
+          >
+        </test-pharos-radio-group>
+      `
+    );
+    const groupDescID = component.renderRoot
+      .querySelector('fieldset')
+      ?.getAttribute('aria-describedby');
+
+    expect(component.renderRoot.querySelector('#' + groupDescID)?.textContent)?.to.equal(text);
```
Comment (daneah) [inline packages/pharos/src/components/radio-group/pharos-radio-group.test.ts:350]:
```suggestion
    expect(component.renderRoot.querySelector(`#${groupDescID}`)?.textContent)?.to.equal(text);
```

**Review by brentswisher — APPROVED** [review]
